language: node_js
node_js:
  - 12

install:
  - npm install

script:
  - npm test

notifications:
  email:
    recipients:
      - lav@yoctu.com

deploy:
  provider: npm
  email: "lav@yoctu.com"
  api_key: "9ce13a42-8d35-4bfe-9bed-5846ee4b3b57"
  edge: true
  on:
    branch: master
